### ISSUE TITLE
Yarn does not working

### ISSUE THREAD

**Issue by codezninja** [thisismydesign/ruby-node-alpine#1]
This is really cool idea. But why doesn't yarn work? When running the following command even though yarn binary is copied over yarn binary doesn't work.

```bash
docker run -it --rm  thisismydesign/ruby-node-alpine:3.0.3-16.13.0-alpine yarn -v
```

**Comment by thisismydesign** [comment]
I'm not sure yarn is included with node by default, you can install it via npm though.

**Comment by codezninja** [comment]
This [line](https://github.com/thisismydesign/ruby-node-alpine/blob/4a7c53c19bd6fe49441a7f86050d85743d415c13/Dockerfile#L11) is coping all the binaries from the node image and yarn seems to be one of them.

### node image

```bash
docker run -it --rm  node:16.13.0-alpine ls /usr/local/bin/
```

![image](https://user-images.githubusercontent.com/4400773/163716787-1e3b9f19-e3c4-4fcb-bed2-63f669ebe114.png)


## ruby-node-alpine

```bash
docker run -it --rm  thisismydesign/ruby-node-alpine:3.0.3-16.13.0-alpine ls /usr/local/bin/
```
![image](https://user-images.githubusercontent.com/4400773/163716699-a1e67b17-6e01-4189-9f74-8902abde461a.png)


Because of that you really can't install yarn since the binary exists in the image already.

Maybe we limit the line to copy only node if the purpose of the image is only add support for node and recommend users to install npm packages manually. But it's a bummer since npm works as intended just not yarn.

**Comment by codezninja** [comment]
Digging into it seems like `yarn` in the nodejs image is actually a symlink to a directory in `/opt/` 
![image](https://user-images.githubusercontent.com/4400773/163717659-796ef9ad-da1f-4000-9407-4f27ab5e5a98.png)

I can open a PR to fix that if that's an acceptable fix?
